services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      DATABASE_URL: postgresql://student_directory_user:cBw13xAiVUAkuy1MS07aONJhCHGzb648@dpg-d7mk3raqqhas73fdqs10-a.oregon-postgres.render.com/student_directory?sslmode=require